---
title: Dialog
lang: de
format:
    html:
        toc: true
---

# Lernen, Ausprobieren, Nachfragen

Sie lesen gerade eine Online-Dokumentation und haben einiges ausprobiert? Vieles haben wir noch nicht ausreichend beschrieben, und Teile der Programmierungen sind in einem frühen Stadium -- also mitunter fehlerhaft und zu kurz gedacht. Oder manchmal sind Schlüsselinformationen schlecht positioniert. Bitte wenden Sie sich direkt an die angegebenen Kontakt-Adressen! Wir geben gern Starthilfe.

Diese Beratung ist Teil unseres Auftrages und entspricht unserem Selbstverständnis. Die Software kann nur gewinnen, wenn sich Nutzer*innen melden. Wir setzen natürlich Prioritäten bei Weiterentwicklungen und Dokumentationen. Nur wer mit uns in Kontakt tritt, kann diese Prioritäten beeinflussen.

# Issues/Tickets

Unsere Arbeit basiert auf dem Ticket-System von GitHub. Alle Arbeitsschritte werden hier vorbereitet und nach Abschluss archiviert. Bitte schauen Sie dort einmal vorbei - dann sehen Sie, was wir in näherer Zunkunft vorhaben und können auch die Diskussion über neue Funktionen direkt verfolgen.

Setzen Sie selbst Ideen, Hinweise oder Fehlerberichte als Ticket in GitHub! Wir melden uns dann bzw. antworten direkt in das Ticketsystem.

# Mailinglisten, Treffen

In den Dokumentationen sind Mailinglisten angegeben, die Sie gern abonnieren können. Hier werden auch Termine von Treffen bekanntgegeben, wie z. B. das jährliche Verona-Forum.

# Erstkontakt

Für eine erste allgemeine Anfrage können Sie folgende E-Mail nutzen:

[iqb-tbadev@hu-berlin.de](mailto:iqb-tbadev@hu-berlin.de)

Verantwortlich für die Inhalte der Seiten und für die Programmierungen ist

Martin Mechtel<br/>
Leiter IT<br/>
Tel: (030) 2093.46960<br/>
[mechtel@iqb.hu-berlin.de](mailto:mechtel@iqb.hu-berlin.de)