---
lang: de
listing:
  id: gallery
  template: start/gallery.ejs
  contents: start/tiles.yml
  type: grid
---

::: {#gallery}
:::

### Testcenter -- Web-Anwendung zum Testen

* [Installation/Code](https://github.com/iqb-berlin/testcenter#readme)
* [Dokumentation für Anwendung](https://github.com/iqb-berlin/iqb-berlin.github.io/wiki/2-Testcenter)
* [Aktuelle Vorhaben](https://github.com/iqb-berlin/testcenter/issues)
* ict-ToolBox - Windows-Programm zur Vor- und Nachbereitung von Testcenter-Daten
  + [Installieren](https://www.iqb.hu-berlin.de/institut/ab/it/itc-ToolBox)
  + [Dokumentation/Code](https://github.com/iqb-berlin/itc-toolbox#readme)


### Studio - Webanwendung zur Bauen von Testaufgaben

* [Installation/Code](https://github.com/iqb-berlin/studio-lite#readme)
* [Dokumentation für Anwendung](https://github.com/iqb-berlin/iqb-berlin.github.io/wiki/3-Studio)
* [Aktuelle Vorhaben](https://github.com/iqb-berlin/studio-lite/issues)

### Verona-Module

* [Aspect Player und Editor](https://github.com/iqb-berlin/verona-modules-aspect/releases) - Player und Editor für komplexe Testaufgaben oder Seiten (IQB-Standard, VERA)
* [Abi Player](https://github.com/iqb-berlin/verona-player-abi/releases) - Player für eine spezielle Scriptsprache
* [Speed Test Player](https://github.com/iqb-berlin/verona-player-speedtest/releases) - Player für Lesegeschwindigkeitstests
* [Simple Player](https://github.com/iqb-berlin/verona-player-simple/releases/latest) - Universeller Player für Html-Definitionen
* [Plain Text Editor](https://github.com/iqb-berlin/verona-editor-plaintext/releases/latest) - Universeller Editor, Bearbeitung der Unit-Definitionen als Text
* [IQB-Schemer](https://github.com/iqb-berlin/coding-components/releases/latest) - Editieren eines Kodierschemas - Standard für IQB-Aufgaben
* Für Entwickler:innen:
  * [Verona-Player-Testbed](https://github.com/iqb-berlin/verona-player-testbed#readme): Anwendung zum Testen von Playern oder Unit-Definitionen
  * [iqb-dev-components](https://github.com/iqb-berlin/iqb-dev-components#readme): Einige allgemeine Tools zur Webentwicklung
