---
title: Spezifikationen
lang: de
format:
    html:
        toc: true
---

Auf dieser Seite finden Sie direkte Links zu Spezifikationen des IQB bzw. zu solchen, an denen das IQB maßgeblich mitgearbeitet hat. Die Spezifikationen sind meist in englischer Sprache gehalten. Soweit verfügbar, sind Verweise auf Erläuterungen der Spezifikationen zu finden, dann auch oft in Deutsch.

# Verona-Module

* Player [Spec](https://verona-interfaces.github.io/player/), [Docs](https://verona-interfaces.github.io/player-docs/)
* Editor [Spec](https://verona-interfaces.github.io/editor/), [Docs](https://verona-interfaces.github.io/editor-docs/); hier findet sich auch die [Variablenliste](https://verona-interfaces.github.io/editor-docs/#parameter-variables)
* Schemer [Spec](https://verona-interfaces.github.io/schemer/), [Docs](https://verona-interfaces.github.io/schemer-docs/)
* Metadaten [Spec](https://verona-interfaces.github.io/metadata/verona-module-metadata.html), [Docs](https://verona-interfaces.github.io/intro/metadata.html)


# IQB-Testcenter

* Input Booklet-Xml: [Spec Xsd](https://github.com/iqb-berlin/testcenter/blob/master/definitions/vo_Booklet.xsd), [Docs](https://pages.cms.hu-berlin.de/iqb/testcenter/pages/booklet-config.html)
* Input Testtaker-Xml: [Spec Xsd](https://github.com/iqb-berlin/testcenter/blob/master/definitions/vo_Testtakers.xsd), [Modi der Testdurchführung](https://pages.cms.hu-berlin.de/iqb/testcenter/pages/test-mode.html)
* Input Unit-Xml: [Spec Xsd](https://github.com/iqb-berlin/testcenter/blob/master/definitions/vo_Unit.xsd)
* Input System-Check-Xml: [Spec Xsd](https://github.com/iqb-berlin/testcenter/blob/master/definitions/vo_SysCheck.xsd)
* Setzen von eigenen Texten -- [CustomTexts](https://pages.cms.hu-berlin.de/iqb/testcenter/pages/custom-texts.html)
* [API Backend](https://pages.cms.hu-berlin.de/iqb/testcenter/dist/api/index.html)

# Antworten/Kodierung

* responses, coding-scheme, missing, state-map: [Spec](https://iqb-berlin.github.io/responses), [Docs](https://iqb-berlin.github.io/coding-info/data-structures/)

# Metadaten

* metadata-profile, profile-store, metadata-values: [Spec](https://iqb-vocabs.github.io/metadata/)
* Datentypen der Metadata-Values: [Spec](https://github.com/iqb-vocabs/metadata/blob/master/docs/value-types.md)
